### ISSUE TITLE
[BUG/Help] <title>ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by xihaofei** [Pillars-Creation/ChatGLM-LoRA#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在尝试运行
CUDA_VISIBLE_DEVICES=0 python finetune_lora_sft.py出现ValueError: 130004 is not in list，请问作者这个该怎么解决呢？

### Steps To Reproduce
(yolov5) root@autodl-container-844a119352-706622cb:~/ChatGLM-RLHF-LoRA-RM-PPO-main/ptuning# CUDA_VISIBLE_DEVICES=0 python finetune_lora_sft.py
[2023-12-28 15:49:42,172] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
12/28/2023 15:49:45 - INFO - utils.common - Process rank: -1, device: cuda:0, n_gpu: 1
  distributed training: False, 16-bits training: True
12/28/2023 15:49:45 - INFO - utils.common - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=8,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=path_to_sft_checkpoint/runs/Dec28_15-49-45_autodl-container-844a119352-706622cb,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=cosine,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=1.0,
optim=adamw_torch,
optim_args=None,
output_dir=path_to_sft_checkpoint,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=1,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=path_to_sft_checkpoint,
save_on_each_node=False,
save_steps=200,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
12/28/2023 15:49:45 - INFO - utils.common - Loading dataset DatasetAttr(load_from='file', dataset_name=None, file_name='sft_data.json', file_sha1='3eaa3bda364ccdd59925d7448a698256c31ef845')...
12/28/2023 15:49:45 - WARNING - utils.common - Checksum failed for data/sft_data.json. It may vary depending on the platform.
/root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/load.py:2479: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
Using custom data configuration default-af7d0652ae9cb6ec
12/28/2023 15:49:46 - INFO - datasets.builder - Using custom data configuration default-af7d0652ae9cb6ec
Loading Dataset Infos from /root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/packaged_modules/json
12/28/2023 15:49:46 - INFO - datasets.info - Loading Dataset Infos from /root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/packaged_modules/json
Overwrite dataset info from restored data version if exists.
12/28/2023 15:49:46 - INFO - datasets.builder - Overwrite dataset info from restored data version if exists.
Loading Dataset info from /root/.cache/huggingface/datasets/json/default-af7d0652ae9cb6ec/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
12/28/2023 15:49:46 - INFO - datasets.info - Loading Dataset info from /root/.cache/huggingface/datasets/json/default-af7d0652ae9cb6ec/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-af7d0652ae9cb6ec/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
12/28/2023 15:49:46 - INFO - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-af7d0652ae9cb6ec/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
Loading Dataset info from /root/.cache/huggingface/datasets/json/default-af7d0652ae9cb6ec/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
12/28/2023 15:49:46 - INFO - datasets.info - Loading Dataset info from /root/.cache/huggingface/datasets/json/default-af7d0652ae9cb6ec/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
[INFO|tokenization_utils_base.py:1800] 2023-12-28 15:49:46,923 >> loading file ice_text.model
[INFO|tokenization_utils_base.py:1800] 2023-12-28 15:49:46,923 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1800] 2023-12-28 15:49:46,923 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1800] 2023-12-28 15:49:46,923 >> loading file tokenizer_config.json
[INFO|configuration_utils.py:666] 2023-12-28 15:49:47,183 >> loading configuration file ChatGLM-6B/model/config.json
[INFO|configuration_utils.py:666] 2023-12-28 15:49:47,222 >> loading configuration file ChatGLM-6B/model/config.json
[INFO|configuration_utils.py:720] 2023-12-28 15:49:47,224 >> Model config ChatGLMConfig {
  "_name_or_path": "ChatGLM-6B/model",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "gmask_token_id": 130001,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "mask_token_id": 130000,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 3,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.27.4",
  "use_cache": true,
  "vocab_size": 130528
}

[INFO|modeling_utils.py:2400] 2023-12-28 15:49:47,293 >> loading weights file ChatGLM-6B/model/pytorch_model.bin.index.json
[INFO|configuration_utils.py:575] 2023-12-28 15:49:47,294 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "pad_token_id": 3,
  "transformers_version": "4.27.4"
}

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:11<00:00,  1.44s/it]
[INFO|modeling_utils.py:3034] 2023-12-28 15:49:58,888 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[INFO|modeling_utils.py:3042] 2023-12-28 15:49:58,888 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at ChatGLM-6B/model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2692] 2023-12-28 15:49:58,966 >> Generation config file not found, using a generation config created from the model config.
12/28/2023 15:49:58 - INFO - utils.common - Fine-tuning method: LoRA
trainable params: 3670016 || all params: 6176956416 || trainable%: 0.0594
Running tokenizer on dataset:   0%|                                                                                                                                      | 0/2000 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "finetune_lora_sft.py", line 112, in <module>
    main()
  File "finetune_lora_sft.py", line 21, in main
    dataset = preprocess_data(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/root/ChatGLM-RLHF-LoRA-RM-PPO-main/ptuning/utils/common.py", line 499, in preprocess_data
    dataset = dataset.map(
  File "/root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/root/miniconda3/envs/yolov5/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/root/ChatGLM-RLHF-LoRA-RM-PPO-main/ptuning/utils/common.py", line 424, in preprocess_supervised_dataset
    context_length = source_ids.index(tokenizer.bos_token_id)
ValueError: 130004 is not in list
### Environment

```markdown
- OS:Ubuntu
- Python:3.8
- Transformers:4.27.4
- PyTorch:1.13.0+cu117
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by Pillars-Creation** [comment]
我这边没遇到你出现的问题，大概率还是你环境有点问题，其它可以运行么？


路上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pillars-Creation/ChatGLM-RLHF-LoRA-RM-PPO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月27日(星期三) 下午4:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Pillars-Creation/ChatGLM-RLHF-LoRA-RM-PPO] [BUG/Help] <title&gt;ModuleNotFoundError: No module named 'datasets' (Issue #7)





 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Current Behavior
 
我在尝试运行bash train.sh时遇到ModuleNotFoundError: No module named 'datasets'，但我已经安装了pip install datasets，依然遇到这个问题。同时，在运行bash ds_train_finetune.sh时遇到ds_train_finetune.sh: line 6: deepspeed: command not found。请问作者上述两个问题该如何解决呢？谢谢。
 
Expected Behavior
 
No response
 
Steps To Reproduce
 
Snipaste_2023-12-27_16-35-00.png (view on web)
 2.png (view on web)
 
Environment
 - OS:Linux - Python:3.8 - Transformers: - PyTorch: - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
 
Anything else?
 
No response
